
services:
  fastapi:
    build: .
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--reload"]
    volumes:
      - ./app:/app
    ports:
      - 8000:8000
    stdin_open: true
    tty: true
    environment:
      - DEBUG=True
      - MARIADB_ROOT_PASSWORD=mysqlpassroot
      - MARIADB_DATABASE=mysqldb
      - MARIADB_USER=mysqldbu
      - MARIADB_PASSWORD=mysqlpass
      - MARIADB_HOST=db
    #depends_on:
    #  - db

  db:
    image: mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: mysqlpassroot
      MARIADB_DATABASE: mysqldb
      MARIADB_USER: mysqldbu
      MARIADB_PASSWORD: mysqlpass
    ports:
      - 3306:3306

volumes:
  mariadb_data:
